api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Users/Domain/Entity'
            - '%kernel.project_dir%/src/Categories/Domain/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
    # formats:
    #     jsonld:   ['application/ld+json']
    #     jsonapi:  ['application/vnd.api+json']

    collection:
        order_parameter_name: '_order'
