doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '13'

        types:
            token: App\Shared\Infostructure\Database\ORM\Type\TokenType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            # App\Shared:
            #     is_bundle: false
            #     type: annotation
            #     dir: '%kernel.project_dir%/src/Shared/Domain/Entity'
            #     prefix: 'App\Shared\Domain\Entity'
            #     alias: App

            App\Users:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Users/Domain/Entity'
                prefix: 'App\Users\Domain\Entity'
                alias: App

            App\Categories:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Categories/Domain/Entity'
                prefix: 'App\Categories\Domain\Entity'
                alias: App

