
gesdinet_jwt_refresh_token:
    token_parameter_name: refreshToken
    single_use: true
    №refresh_token_class: App\Context\Common\Domain\Entity\JwtRefreshToken
    cookie:
      enabled: true
      same_site: lax               # default value
      path: /                      # default value
      domain: null                 # default value
      http_only: true              # default value
      secure: false                 # default value
      remove_token_from_body: true # default value